### ISSUE TITLE
Error: Cannot destructure property 'path' of 'flags' as it is undefined

### ISSUE THREAD

**Issue by alessandro-newzoo** [newrelic/nr1-github#108]
## Description

I'm trying to run `nr1 nerdpack:clone -r https://github.com/newrelic/nr1-github.git` but I constantly get this error and no cloning will happen:

```bash
nr1 nerdpack:clone -r https://github.com/newrelic/nr1-github.git
 ›   Error: Cannot destructure property 'path' of 'flags' as it is undefined.
 ›   Code: UNKNOWN
```

## Steps to Reproduce

- Download and install installer.pkg from https://one.newrelic.com/developer-center?account=<REDACTED>
- in Terminal, run `nr1 profiles:add --name account-<REDACTED> --api-key NRAK-<REDACTED> --region us`
- in Terminal, run `nr1 nerdpack:clone -r https://github.com/newrelic/nr1-github.git`
- the error pops up.

## Expected Behaviour

The command should clone the git repo

## Relevant Logs / Console output

<img width="873" alt="image" src="https://user-images.githubusercontent.com/47320294/233978630-c75bd6be-64ef-4905-a8ca-90b24e03d097.png">

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: `@datanerd/nr1/2.83.5 darwin-x64 node-v16.11.1`
* Node version: `v18.13.0`
* Operating System and version: `macOS 13.3`

**Comment by alessandro-newzoo** [comment]
actually I've bumped into the same issue with another package `nr1 nerdpack:clone -r https://github.com/newrelic/nr1-browser-analyzer.git` so I guess the problem comes from the NR1 CLI. Apologies I'll post my issue somewhere else then!

**Comment by kassi** [comment]
@alessandro-newzoo could you paste a link to the other issue? Couldn't figure out where to post it. Running into the same issue. Also running into other issues after cloning via git though.
