### ISSUE TITLE
Unable to find nerd pack in New Relic hosted instance

### ISSUE THREAD

**Issue by dcilia** [newrelic/nr1-github#111]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Following the steps in this repository, I am able to clone & serve the nerd pack locally.  Following the url: 
https://one.newrelic.com/?nerdpacks=local

I am unable to find the nerd pack or configure it.  The screenshots in the Readme reference a configuration page?  I am unable to get to that. 

## Steps to Reproduce

Follow all the steps in the readme.  Try to find the nerd pack, it is missing.

## Expected Behaviour

Should be able to see the nerd pack (and configure it??)

## Relevant Logs / Console output

N/A

## Your Environment

os:
macOS Sonoma 14.2.1
cli version:
@datanerd/nr1/2.83.5 darwin-x64 node-v16.11.1

web browser:
Safari Version 17.2.1 (19617.1.17.11.12)

**Comment by aso1124** [comment]
Hi @dcilia  - Were you looking for the nerdpack in the Apps section? If not, you find that either already visible in the left navigation menu, or by clicking on the more option at the bottom of the left nav menu

**Comment by dcilia** [comment]
Hi @aso1124 I don't see it in either case.  I was able to find it navigating through the apps and looking at all the apps.

I attached some screenshots.  Can you take a look and advise on next steps?

<img width="1071" alt="screen1" src="https://github.com/newrelic/nr1-github/assets/992986/ce4052b2-fde4-4557-953f-c07c8a3a0d55">
![screen2](https://github.com/newrelic/nr1-github/assets/992986/92723dad-1dd7-4fbb-b58c-d77625b46d4d)

**Comment by dcilia** [comment]
Hi, I was able to navigate and find the integration as well as configure an app with it.  I am going to close this, but feel free to re-open if you have any follow ups.
