### ISSUE TITLE
Install Error - PATH not updated, Original length 1171 > 1024

### ISSUE THREAD

**Issue by tyler-fleming** [newrelic/nr1-github#19]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When I try to install the CLI using the installer I get an error that says `PATH not updated, Original length 1171 > 1024`
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Download installer from https://one.newrelic.com/launcher/developer-center.launcher and follow normal steps of install
[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour
Software is installed and path is updated
[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
The download log looks like everything is installed but this is at the end of the log.
`Output folder: C:\Program Files\newrelic-cli`
`Created uninstaller: C:\Program Files\newrelic-cli\Uninstall.exe`
`AddToPath: original length 1171 > 1024`
`ExecShell: `
`Completed`
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: Trying to install nr1 CLI 1.2.2
* Browser name and version: Chrome
* Operating System and version: Windows 10 Enterprise

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by tangollama** [comment]
@tyler-fleming apologies that I missed this report. It's not precisely related to the GitHub app. As such, I'm going to close it; but if you're having trouble installing the CLI, I'd direct you yo our Explorers Hub to seek assistance.
