### ISSUE TITLE
Fix other nerdpack vulnerability

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/nr1-github#69]
We had a report of a vulnerability in this nerdpack that we'll want to resolve. please refer to the internal JIRA issue for specifics

### Acceptance Criteria 

- see Ticket ID: `jira/INFOSEC-3218`
- resolve issue 
- deploy the update via the catalog manager to the EU / Stage and Prod env

**Comment by nr-kkenney** [comment]
pr was merged, but gonna leave this open until all environments are updated (production, eu, staging).

**Comment by nr-kkenney** [comment]
eu & staging have been updated. closing.
