### ISSUE TITLE
A user can no longer set a GitHub URL universally for an org

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-github#79]
A user can no longer set a GitHub URL universally, each user must set this individually, and they are stored in that users secrets vault. This prevents one user from setting the GitHub URL to a fake server, and stealing another users PAT when they use the NerdPack

### Acceptance Criteria 

- [x] A user sets a PAT and now in order for them to have access to the Repo each person needs to configure their own instance of the github url and repo url.
- [x] Review the repo [readme](https://github.com/newrelic/nr1-github#readme) and update if necessary.
- [x] confirm if this change will break any existing users github configurations.
- [x] When the nerdpack version is updated provide a warning message that notifies the user of this change.  - We may not need to do this if we can ensure we aren't breaking any existing configurations for users.

**Comment by rudouglas** [comment]
This is what the experience is now. 

If a user has set an Enterprise GitHub URL for the App, they will now be directed to the `Setup` section and have to set it again. They will now see this Callout which will include the URL they set previously so they can easily set it again.


<img width="1048" alt="Screenshot 2021-06-14 at 11 50 18" src="https://user-images.githubusercontent.com/17122543/121929805-86016380-cd39-11eb-89d5-4781da2608f0.png">

Thinking about it I just thought of an edge case that i need to test so will update this again before review

**Comment by jpvajda** [comment]
@rudouglas awesome. it's always great to catch those edge cases. 👍

**Comment by rudouglas** [comment]
@jpvajda i've made those changes so this is ready for review

**Comment by jpvajda** [comment]
@rudouglas I'm unable to validate this locally, as I get this error, I think we just need to pair to run through it tomorrow. Shouldn't take long.

<img width="426" alt="Screen Shot 2021-06-14 at 4 06 06 PM" src="https://user-images.githubusercontent.com/1395158/121965896-fc4a9980-cd2a-11eb-8348-9cba2c4e1b91.png">

**Comment by jpvajda** [comment]
I've pull down this PR, run NPM Install and nerdpack:serve and see this, but I can't seem to pull up the code locally.

<img width="748" alt="Screen Shot 2021-06-14 at 4 10 37 PM" src="https://user-images.githubusercontent.com/1395158/121966075-3fa50800-cd2b-11eb-91c8-d58038ef4109.png">

**Comment by rudouglas** [comment]
You may need to regenerate the GUID. Could you pull down the latest branch and run:

```bash
nr1 nerdpack:uuid -gf
npm install
npm start
```

Also make sure you are on the right profile for your account:

```bash
nr1 profiles:default
```

The other thing is that the reproduction of the new behaviour requires you to publish the Nerdpack to your account, and access it with 2 different users, maybe we should 🏕️ it later @jpvajda

**Comment by jpvajda** [comment]
Feedback from our review of this today: @rudouglas 

`1`. the tooltip should be more explicit telling the user what to do. 

```
We recently made security improvements to this Nerdpack which may require you to setup up your Github URL again.  
The following Github URL was previously set on your account {GITHUB_URL}. 
If this is a trusted source, copy and paste this URL into the field below.

```

`2`. The URL within the field for Github Enterprise should not be clickable. 

`3.` Provide a final screen shot of the experience in the body of this ticket 

`4`.  Ping the Wizards slack channel to make others aware of this change prior to pushing to prod.

**Comment by rudouglas** [comment]
Altered this based on our chat yesterday. Also did some double-checks to make sure this step is not needed for Apps set to the Public GitHub API URL
<img width="896" alt="Screenshot 2021-06-16 at 11 49 56" src="https://user-images.githubusercontent.com/17122543/122209212-2f606a80-ce9c-11eb-8c63-01e41b6d93c2.png">

**Comment by rudouglas** [comment]
Made changes in the latest push and notified `#wizards-programmability`

**Comment by jpvajda** [comment]
By end of day if we don't hear any concerns on this change, we can deploy it. I'll keep an eye on the 🧙 channel.

**Comment by jpvajda** [comment]
I didn't see any concerns in the Wizards channel, so let's deploy this change 🥳
