### ISSUE TITLE
"Github Repo" link appears twice in side bar in staging

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-github#92]
This was identified during our company wide bug hunt quality event, so it's higher priority. 

Please see the JIRA issue for a lot more details

Related issue: `JIRA  DEVEX-2336`

Steps to reproduce 

1. Go to staging > browser applications > more views 
2. see 2 entries for Github Repo

### Expected

Only 1 entry for github repo is visible.

### Screen shot

![index](https://user-images.githubusercontent.com/1395158/156857686-6a493efe-491b-41fb-8c38-a17d7a4d7e25.png)

**Comment by jpvajda** [comment]
I went into staging, and the UI for explorer is completely different from this screen shot so I'm having a tough time seeing this issue at the moment.

**Comment by jpvajda** [comment]
So now I was able to double check this, and now I don't see 2 GH Repo menu items...

<img width="278" alt="Screen Shot 2022-03-07 at 8 45 02 AM" src="https://user-images.githubusercontent.com/1395158/157067642-91761ec7-dc2b-4797-8ed5-86a6726e2723.png">

**Comment by jpvajda** [comment]
But there seems to be 2 in nergraph, and the JIRA ticket has more details on the query you can use to see those

**Comment by LizBaker** [comment]
This can happen when the same app is published under two different UUIDs. In this case we know the global app's UUID so we can easily see which is the dupe. It appears it was only an issue on staging and has been unsubscribed and untagged so it should no longer show up for any account
